import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
  homeWrapper: {
    // paddingTop: 30,
    // paddingHorizontal: 20,
    paddingLeft: 20,
    height: "100%",
    backgroundColor: "#F8FBFF",
    // backgroundColor: "red",
  },
  /* Body */
  homeWrapperBody: {
    // backgroundColor: "red",
    // marginBottom: 100,
  },
  homeWrapperBodyHeader: {
    // style here
    // paddingVertical: 40,
  },
  homeWrapperBodyHeaderTitle: {
    color: "#3D3D3D",
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 31,
    marginVertical: 20,
  },
  homeWrapperBodyHeaderType: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 20,
  },
  homeWrapperBodyHeaderTypeBoxOutside: {
    borderWidth: 1,
    borderRadius: 50,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  homeWrapperBodyHeaderTypeBoxInside: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    paddingVertical: 30,
    paddingHorizontal: 10,
    margin: 10,
    borderRadius: 50,
  },
  homeWrapperBodyHeaderTypeBoxInsideTitle: {
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 18,
    color: "#000000",
  },
  homeWrapperBodyContent: {
    // backgroundColor: "red",
  },
  homeWrapperBodyContentTop: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 20,
  },
  homeWrapperBodyContentTopLeft: {
    fontWeight: "700",
    fontSize: 16,
    lineHeight: 21,
    color: "#3D3D3D",
  },
  homeWrapperBodyContentTopRight: {
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 21,
    color: "#FE554A",
    textDecorationLine: "underline",
    paddingRight: 20,
  },
  homeWrapperBodyContentBottom: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 35,
  },
  homeWrapperBodyContentBottomBox: {
    backgroundColor: "#FFFFFF",
    borderRadius: 30,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    width: 220,
    // height: 260,
    padding: 16,
  },
  BottomBoxImg: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  homeWrapperBodyContentBottomBoxName: {
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 21,
    color: "#3D3D3D",
    marginTop: 15,
    marginBottom: 5,
  },
  homeWrapperBodyContentBottomBoxDes: {
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 18,
    color: "#3D3D3D",
    marginBottom: 12,
  },
  homeWrapperBodyContentBottomFooter: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  homeWrapperBodyContentBottomFooterRate: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
  },
  homeWrapperBodyContentBottomFooterRateText: {
    fontWeight: "400",
    fontSize: 13,
    lineHeight: 18,
    color: "#3D3D3D",
  },
  /* End of Body */
});
