import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
  homeWrapper: {
    paddingTop: 30,
    paddingHorizontal: 20,
    height: "100%",
    backgroundColor: "#F8FBFF",
  },
  /* Header */
  homeWrapperHeader: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    // backgroundColor: "green",
  },
  homeWrapperHeaderLeft: {
    width: 40,
    height: 40,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
  },
  shadowProp: {
    shadowColor: "#red",
    shadowOffset: { width: -2, height: 30 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  homeWrapperHeaderCenter: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
  },
  homeWrapperHeaderCenterTop: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
  },
  homeWrapperHeaderCenterTopTitle: {
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 21,
    textDecorationLine: "underline",
    color: "#1C1C1C",
  },
  homeWrapperHeaderCenterTopIcon: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  homeWrapperHeaderCenterBottom: {
    fontWeight: "400",
    fontSize: 15,
    lineHeight: 23,
    color: "#FE554A",
  },
  homeWrapperHeaderRight: {
    width: 40,
    height: 40,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
  },
  /* End of Header */
  /* Body */
  homeWrapperBody: {
    // backgroundColor: "red",
    // marginBottom: 100,
    height: "100%",
  },
  homeWrapperBodyHeader: {
    // style here
    // paddingVertical: 40,
  },
  homeWrapperBodyHeaderTitle: {
    color: "#3D3D3D",
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 31,
    marginVertical: 20,
  },
  homeWrapperBodyHeaderType: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 20,
  },
  homeWrapperBodyHeaderTypeBoxOutside: {
    borderWidth: 1,
    borderRadius: 50,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  homeWrapperBodyHeaderTypeBoxInside: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    paddingVertical: 30,
    paddingHorizontal: 10,
    margin: 10,
    borderRadius: 50,
  },
  homeWrapperBodyHeaderTypeBoxInsideTitle: {
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 18,
    color: "#000000",
  },
  homeWrapperBodyContent: {
    // backgroundColor: "red",
  },
  homeWrapperBodyContentTop: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 20,
  },
  homeWrapperBodyContentTopLeft: {
    fontWeight: "700",
    fontSize: 16,
    lineHeight: 21,
    color: "#3D3D3D",
  },
  homeWrapperBodyContentTopRight: {
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 21,
    color: "#FE554A",
    textDecorationLine: "underline",
  },
  homeWrapperBodyContentBottom: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 35,
  },
  homeWrapperBodyContentBottomBox: {
    backgroundColor: "#FFFFFF",
    borderRadius: 30,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    width: 220,
    // height: 260,
    padding: 16,
  },
  BottomBoxImg: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  homeWrapperBodyContentBottomBoxName: {
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 21,
    color: "#3D3D3D",
    marginTop: 15,
    marginBottom: 5,
  },
  homeWrapperBodyContentBottomBoxDes: {
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 18,
    color: "#3D3D3D",
    marginBottom: 12,
  },
  homeWrapperBodyContentBottomFooter: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  homeWrapperBodyContentBottomFooterRate: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
  },
  homeWrapperBodyContentBottomFooterRateText: {
    fontWeight: "400",
    fontSize: 13,
    lineHeight: 18,
    color: "#3D3D3D",
  },
  /* End of Body */
  /* Footer */
  homeWrapperFooter: {
    backgroundColor: "#FFFFFF",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 20,
    paddingBottom: 40,
    paddingHorizontal: 30,
    marginTop: 20,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    position: "relative",
  },
  homeWrapperFooterBox: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 40,
  },
  homeWrapperFooterBoxIcon: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  homeWrapperFooterBoxSearch: {
    position: "absolute",
    top: -50,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  searchBoxItem: {
    position: "absolute",
    top: -80,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  searchBox: {
    width: 60,
    height: 60,
    backgroundColor: "#faf8f7",
    borderRadius: 60,
  },
  /* End of Footer */
});
