import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
  productDetailWrapper: {
    backgroundColor: "#F8FBFF",
    height: "100%",
  },
  productDetailWrapperBoxImage: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
    // backgroundColor: "red",
  },
  productDetailWrapperDetailImage: {
    backgroundColor: "#FFFFFF",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 20,
    paddingBottom: 30,
    borderRadius: 20,
    width: 258,
    height: 224,
  },
  productDetailWrapperImage: {
    maxWidth: "100%",
    width: "100%",
    height: 150,
    objectFit: "contain",
  },
  productDetailWrapperBoxNumber: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  productDetailWrapperBoxNumberDetail: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    height: 50,
    width: 100,
  },
  productDetailWrapperBoxNumberText: {
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 21,
    color: "#FFFFFF",
    padding: 12,
  },
  productDetailWrapperBoxTitle: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    padding: 25,
  },
  productDetailWrapperBoxTitleText: {
    fontWeight: "700",
    fontSize: 24,
    lineHeight: 31,
    color: "#3D3D3D",
    textTransform: "capitalize",
  },
  productDetailWrapperBoxTitleUnde: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 30,
  },
  productDetailWrapperBoxTitleUndeIcon: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
  },
  productDetailWrapperBoxTitleUndeIconText: {
    fontWeight: "400",
    fontSize: 11,
    lineHeight: 16,
    color: "#3D3D3D",
  },
  productDetailWrapperBoxDes: {
    paddingHorizontal: 30,
  },
  productDetailWrapperBoxDesText: {
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 21,
    color: "#3D3D3D",
  },
  productDetailWrapperBoxTopping: {
    paddingLeft: 30,
    paddingTop: 25,
    paddingBottom: 25,
  },
  productDetailWrapperBoxToppingText: {
    fontWeight: "500",
    fontSize: 18,
    lineHeight: 24,
    color: "#3D3D3D",
    marginBottom: 16,
  },
  productDetailWrapperBoxToppingList: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 20,
  },
  productDetailWrapperBoxToppingListItem: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    // borderWidth: 1,
    // borderColor: "#F9881F",
    padding: 16,
    borderRadius: 30,
  },
  productDetailWrapperBoxToppingListItemText: {
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 21,
    color: "#3D3D3D",
  },
  productDetailWrapperBoxAdd: {
    backgroundColor: "#fc7d32",
    marginHorizontal: 30,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 20,
    borderRadius: 30,
    // marginTop: 20,
  },
  productDetailWrapperBoxAddText: {
    fontWeight: "700",
    fontSize: 16,
    lineHeight: 21,
    color: "#FFFFFF",
    textTransform: "capitalize",
  },
});
