import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
  homeWrapperHeader: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    backgroundColor: "#F8FBFF",
  },
  homeWrapperHeaderLeft: {
    width: 40,
    height: 40,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
  },
  shadowProp: {
    shadowColor: "#red",
    shadowOffset: { width: -2, height: 30 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  homeWrapperHeaderCenter: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
  },
  homeWrapperHeaderCenterTop: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
  },
  homeWrapperHeaderCenterTopTitle: {
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 21,
    textDecorationLine: "underline",
    color: "#1C1C1C",
  },
  homeWrapperHeaderCenterTopIcon: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  homeWrapperHeaderCenterBottom: {
    fontWeight: "400",
    fontSize: 15,
    lineHeight: 23,
    color: "#FE554A",
  },
  homeWrapperHeaderRight: {
    width: 40,
    height: 40,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
  },
});
